# This is a basic workflow to help you get started with Actions

name: Fetch CA Vaccination Data

# Controls when the action will run.
on:
  # Trigger on schedule
  schedule:
    - cron: '0 */2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Setup Selenium
        uses: nanasess/setup-chromedriver@master
        run: |
              export DISPLAY=:99
              chromedriver --url-base=/wd/hub &
              sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Run fetch_vax_by_group
        run: |
          python src/fetch_vax_by_group.py
      - name: Commit data to repo
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f data/raw/county_vaccine_data/*
          git commit -m "Fetching CA vaccine data"
      - name: Push data to repo
        uses: ad-m/github-push-action@master
        with:
          github_token: $ {{secrets.fetch_ca_vax_token }}
